vim.g.mapleader = " "

require("plugins/nvim_web_devicons")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/nvim_treesitter_context")
require("plugins/gitsigns")
require("plugins/satellite")
require("plugins/hlsearch")
require("plugins/meow_yarn")
require("plugins/goto_preview")
require("plugins/mason")
require("plugins/nvim_lspconfig")
require("plugins/blink_cmp")
require("plugins/tiny_inline_diagnostic")
require("plugins/lua_ls")
require("plugins/mason_lspconfig")
require("plugins/theme_hub")
require("plugins/nvim_autopairs")
require("plugins/lualine")
require("plugins/yanky")
require("plugins/resession")
require("plugins/conform")

require("editor")
require("colorscheme")
require("tree")
require("keymaps")
